import Head from "next/head";
// import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Image from "next/image";
import Link from "next/link";
// const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }) {
  return (
    <>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <header>
          <nav>
         
              <Link href="/" passHref>
                <h2> Home</h2>
              </Link>
              <Link href="/events" passHref>
                <h2> Events</h2>
              </Link>
              <Link href="/about-us" passHref>
                <h2> About Us</h2>
              </Link>
            
          </nav>
        </header>
        <main className={styles.main}>
          {data.map((ev) => (
            <Link key={ev.id} href={`/events/${ev.id}`} passHref>
              <Image
                width={"200"}
                height={"200"}
                alt={ev.title}
                src={ev.image}
              />{" "}
              <h2>{ev.title}</h2>
              <p>{ev.description}</p>
            </Link>
          ))}
        </main>

        <footer className={styles.footer}></footer>
      </div>
    </>
  );
}
export async function getServerSideProps() {
  const { events_categories } = await import("/data/data.json");
  console.log(events_categories);

  return {
    props: {
      data: events_categories,
    },
  };
}
